
server:
  port: 8002

api:
  key: '63NJUA45A97BF6OI'
  timeout: 3000


spring:
  application:
    name: Finance-forex
  output:
    ansi:
      enabled: ALWAYS
  data:
    mongodb:
      uri: mongodb://financeuser:financepassword5000@146.59.195.214:27017/finance?retryWrites=true&w=majority
      database: finance
  main:
    allow-bean-definition-overriding: true
  boot:
    admin:
      client:
        url: http://146.59.195.214:9090
        instance:
          management-url: http://146.59.195.214:9090/actuator
          health-url: http://146.59.195.214:9090/actuator/health
          service-url: http://146.59.195.214:9090

logging.level.org.springframework.security: DEBUG

management:
  security:
    enabled: false
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: '*'
